experiment_name: "experiment1"

paths:
  data: "/net/ens/am4ip/datasets/project-dataset"

dataset_split:
  train: 0.80  # Percentage of data for training
  val: 0.1    # Percentage of data for validation
  test: 0.1   # Percentage of data for testing

data:
  shuffle: true      # Shuffle data during loading
  num_workers: 4     # Number of workers for data loading
  pin_memory: true   # Enable pin_memory for better performance on GPU

hyperparameters:
  batch_size: 16
  learning_rate: 1e-5
  epochs: 50
  seed: 42
  input_channels: 3
  output_channels: 31
  mixed_precision: true

model:
  name: "UNet"  # Options: UNet, DeepLabV3Plus, etc.
  pretrained: false

loss:
  name: "TverskyLoss"  # Options: CrossEntropyLoss, FocalLoss, etc.
  params: {}  # Additional parameters for the loss function

optimizer:
  name: "Adam"  # Options: Adam, SGD, etc.
  params:
    lr: 0.0001
    weight_decay: 0.0001

scheduler:
  name: "CosineAnnealingLR"
  params:
    T_max: 10
    eta_min: 0.000001

metrics:
  iou: true
  pixel_accuracy: true
  dice: true

early_stopping:
  enabled: true
  patience: 5
  metric: "val_loss"


# hyperparameters:
#   batch_size: 16
#   learning_rate: 1e-4
#   epochs: 5
#   seed: 42
#   input_channels: 3
#   output_channels: 31
#   mixed_precision: true



# scheduler:
#   name: "StepLR"
#   params:
#     step_size: 5
#     gamma: 0.5


augmentation:
  use_augmentation: false
  params:
    horizontal_flip: true
    rotation_range: 15
    brightness_adjust: 0.2
    contrast_adjust: 0.2
    scale_range: [0.8, 1.2]
    gaussian_noise: 0.05
    random_crop: [256, 256]

logging:
  log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR
  tensorboard: true
  gradient_monitoring: true

evaluation:
  use_test_set: true
  batch_size: 16

class_to_color:
  0: [0, 0, 0]        # Unlabeled
  1: [0, 0, 0]        # Static
  2: [111, 74, 0]     # Dynamic
  3: [81, 0, 81]      # Ground
  4: [128, 64, 128]   # Road
  5: [244, 35, 232]   # Sidewalk
  6: [250, 170, 160]  # Parking
  7: [230, 150, 140]  # Rail track
  8: [70, 70, 70]     # Building
  9: [102, 102, 156]  # Wall
  10: [190, 153, 153] # Fence
  11: [180, 165, 180] # Guard rail
  12: [150, 100, 100] # Bridge
  13: [150, 120, 90]  # Tunnel
  14: [153, 153, 153] # Pole
  15: [153, 153, 153] # Pole group
  16: [250, 170, 30]  # Traffic light
  17: [220, 220, 0]   # Traffic sign
  18: [107, 142, 35]  # Vegetation
  19: [152, 251, 152] # Terrain
  20: [70, 130, 180]  # Sky
  21: [220, 20, 60]   # Person
  22: [255, 0, 0]     # Rider
  23: [0, 0, 142]     # Car
  24: [0, 0, 70]      # Truck
  25: [0, 60, 100]    # Bus
  26: [0, 0, 90]      # Caravan
  27: [0, 0, 110]     # Trailer
  28: [0, 80, 100]    # Train
  29: [0, 0, 230]     # Motorcycle
  30: [119, 11, 32]   # Bicycle

class_names:
  - Unlabeled
  - Static
  - Dynamic
  - Ground
  - Road
  - Sidewalk
  - Parking
  - Rail track
  - Building
  - Wall
  - Fence
  - Guard rail
  - Bridge
  - Tunnel
  - Pole
  - Pole group
  - Traffic light
  - Traffic sign
  - Vegetation
  - Terrain
  - Sky
  - Person
  - Rider
  - Car
  - Truck
  - Bus
  - Caravan
  - Trailer
  - Train
  - Motorcycle
  - Bicycle