experiment_name: "unet_resnet_cross"

paths:
  data: "/net/ens/am4ip/datasets/project-dataset"

dataset_split:
  train: 0.80  # Percentage of data for training
  val: 0.1    # Percentage of data for validation
  test: 0.1   # Percentage of data for testing

data:
  shuffle: true      # Shuffle data during loading
  num_workers: 4     # Number of workers for data loading
  pin_memory: true   # Enable pin_memory for better performance on GPU

hyperparameters:
  batch_size: 16
  learning_rate: 1e-5
  epochs: 50
  seed: 42
  input_channels: 3
  output_channels: 34
  mixed_precision: true

model:
  name: "UNetWithResNet"  # Options: UNet, DeepLabV3Plus, etc.
  pretrained: true
  backbone: resnet50
  use_dropout: False

loss:
  name: "CrossEntropyLoss"  # Options: CrossEntropyLoss, FocalLoss, etc.
  params: {}  # Additional parameters for the loss function

optimizer:
  name: "Adam"  # Options: Adam, SGD, etc.
  params:
    lr: 0.0001
    weight_decay: 0.0001

scheduler:
  name: "CosineAnnealingLR"
  params:
    T_max: 10
    eta_min: 0.000001

metrics:
  iou: true
  pixel_accuracy: true
  dice: true

early_stopping:
  enabled: false
  patience: 5
  metric: "val_loss"


# hyperparameters:
#   batch_size: 16
#   learning_rate: 1e-4
#   epochs: 5
#   seed: 42
#   input_channels: 3
#   output_channels: 31
#   mixed_precision: true



# scheduler:
#   name: "StepLR"
#   params:
#     step_size: 5
#     gamma: 0.5


augmentation:
  use_augmentation: false
  params:
    horizontal_flip: true
    rotation_range: 15
    brightness_adjust: 0.2
    contrast_adjust: 0.2
    scale_range: [0.8, 1.2]
    gaussian_noise: 0.05
    random_crop: [256, 256]

logging:
  log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR
  tensorboard: true
  gradient_monitoring: true

evaluation:
  use_test_set: true
  batch_size: 16


class_names:
  - Unlabeled
  - Unused
  - Unused
  - Unused
  - Static
  - Dynamic
  - Ground
  - Road
  - Sidewalk
  - Parking
  - Rail track
  - Building
  - Wall
  - Fence
  - Guard rail
  - Bridge
  - Tunnel
  - Pole
  - Pole group
  - Traffic light
  - Traffic sign
  - Vegetation
  - Terrain
  - Sky
  - Person
  - Rider
  - Car
  - Truck
  - Bus
  - Caravan
  - Trailer
  - Train
  - Motorcycle
  - Bicycle